#!/bin/sh
#    CFLAGS="-g" \

./configure \
    --prefix=`brew --prefix` \
    --with-features=huge \
    --with-compiledby="yukpiz <yukpiz@gmail.com>" \
    --with-lua-prefix=/usr/local \
    --without-x \
    --enable-fail-if-missing \
    --enable-multibyte \
    --enable-luainterp \
    --enable-pythoninterp \
    --enable-rubyinterp \
    --enable-cscope \
    --enable-gui=no \
    --disable-darwin \
    --disable-selinux
