#!/bin/bash

if type ls 2>/dev/null 1>/dev/null
then
    alias ll='ls -alF'
    alias la='ls -A'
    alias l='ls -CF'
fi

if type trash 2>/dev/null 1>/dev/null
then
    alias rm='trash'
fi

if type docker 2>/dev/null 1>/dev/null
then
    alias docker='sudo docker'
fi


if type notify-send 2>/dev/null 1>/dev/null
then
    alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
fi

if type pidcat 2>/dev/null 1>/dev/null
then
    alias logcat='pidcat'
fi

if type vim 2>/dev/null 1>/dev/null
then
    alias vim='vim -X'
fi
