#!/bin/bash

if type ls 2>/dev/null 1>/dev/null
then
    if [ "$(uname)" = 'Darwin' ]; then
        alias ls='ls -G'
        export LSCOLORS=gxfxcxdxcxegedabagacad
    else
        alias ls='ls --color=auto'
    fi
    alias ll='ls -alF'
    alias la='ls -A'
    alias l='ls -CF'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
    alias g='git'
fi

if type trash 2>/dev/null 1>/dev/null
then
    alias rm='trash'
fi

if type docker 2>/dev/null 1>/dev/null
then
    alias docker='sudo docker'
fi


if type notify-send 2>/dev/null 1>/dev/null
then
    alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
fi

if type pidcat 2>/dev/null 1>/dev/null
then
    alias logcat='pidcat'
fi

if type vim 2>/dev/null 1>/dev/null
then
    alias vim='/usr/local/bin/vim'
    alias vim='vim -X'
fi
